/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.c1212l.fs.ui;

import com.c1212l.fs.bean.Customer;
import com.c1212l.fs.bean.Permission;
import com.c1212l.fs.bll.CustomerBUS;
import com.c1212l.fs.bll.PermissionBUS;
import com.c1212l.fs.util.KeyValue;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luu Bi
 */
public class PermissionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PermitPanel
     */
    public PermissionPanel() {
        initComponents();
        reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPermissionID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPermissionName = new javax.swing.JTextField();
        lblProductManager = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPermission = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Permission ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 10));

        txtPermissionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPermissionIDActionPerformed(evt);
            }
        });
        add(txtPermissionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 110, -1));

        jLabel2.setText("Permission Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        add(txtPermissionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        lblProductManager.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProductManager.setText("Permission Manager");
        add(lblProductManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 180, 60, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        tblPermission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPermission);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPermissionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPermissionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPermissionIDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            // TODO add your handling code here:
            String permissionName = txtPermissionName.getText();
            permissionBUS.addPermission(permissionName);
            reloadData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PermissionPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PermissionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProductManager;
    private javax.swing.JTable tblPermission;
    private javax.swing.JTextField txtPermissionID;
    private javax.swing.JTextField txtPermissionName;
    // End of variables declaration//GEN-END:variables
    private PermissionBUS permissionBUS = new PermissionBUS();
    DefaultTableModel tblModel;
    ArrayList<Customer> lstPermission;    

    private void initTable() {
        Vector header = new Vector();
        header.add("Permission ID ");
        header.add("Permission Name");
        tblModel = new DefaultTableModel(header, 0);
        tblPermission.setModel(tblModel);
    }

    private void fillData(ArrayList<Permission> lst) {
        if (lst != null) {
            for (Permission permission : lst) {
                tblModel.addRow(permission.getVector());
            }
        }
    }

    private void reloadData() {
        try {
            initTable();
            fillData(permissionBUS.getAllPermission());
            initTextField();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void initTextField() {
        txtPermissionID.setText("");
        txtPermissionName.setText("");
    }
}
