/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.c1212l.fs.ui;

import com.c1212l.fs.bean.Category;
import com.c1212l.fs.bean.Customer;
import com.c1212l.fs.bean.Product;
import com.c1212l.fs.bean.Vendor;
import com.c1212l.fs.bll.CategoryBUS;
import com.c1212l.fs.bll.ProductBUS;
import com.c1212l.fs.bll.VendorBUS;
import com.c1212l.fs.util.KeyValue;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luu Bi
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    public ProductPanel() {
        initComponents();
        reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        cmbVendor = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProductDetail = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        jTextField3.setText("jTextField3");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Product ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setText("Product Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel3.setText("Product Detail:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 20));

        jLabel4.setText("Category:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel5.setText("Vendor:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 110, -1));

        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, -1));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 110, -1));

        cmbVendor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVendorActionPerformed(evt);
            }
        });
        add(cmbVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 110, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        btnDelete.setText("Delete");
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Product Manager");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        txtProductDetail.setColumns(20);
        txtProductDetail.setRows(5);
        jScrollPane1.setViewportView(txtProductDetail);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 70));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 410, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void cmbVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVendorActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            // TODO add your handling code here:
            Category category = productBUS.getCategoryID(cmbCategory.getSelectedItem().toString());
            Vendor   vendor = productBUS.getVendorID(cmbVendor.getSelectedItem().toString());
            System.out.println(cmbVendor.getSelectedItem());
            String productName = txtProductName.getText();
            String productDetail = txtProductDetail.getText();
            String categoryID = category.getCategoryID();
            String vendorID = vendor.getVendorID();
            productBUS.addProduct(productName, productDetail, categoryID, vendorID);
            reloadData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ProductPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblProduct.getSelectedRow();
        txtProductID.setText(tblProduct.getValueAt(selectedRow, 0).toString());
        txtProductName.setText(tblProduct.getValueAt(selectedRow, 1).toString());
        txtProductDetail.setText(tblProduct.getValueAt(selectedRow, 2).toString());
        cmbCategory.setSelectedItem(new KeyValue(0, tblProduct.getValueAt(selectedRow, 3).toString()));
        cmbVendor.setSelectedItem(new KeyValue(0, tblProduct.getValueAt(selectedRow, 4).toString()));
    }//GEN-LAST:event_tblProductMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextArea txtProductDetail;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables
   private ProductBUS productBUS = new ProductBUS();
    DefaultTableModel tblModel;
    ArrayList<Customer> lstProduct;    

    private void initTable() {
        Vector header = new Vector();
        header.add("Product ID ");
        header.add("Product Name");
        header.add("Product Detail");
        header.add("Category ");
        header.add("Vendor ");
        header.add("Inventory");
        tblModel = new DefaultTableModel(header, 0);
        tblProduct.setModel(tblModel);
    }

    private void fillData(ArrayList<Product> lst) {
        if (lst != null) {
            for (Product product : lst) {
                tblModel.addRow(product.getVector());
            }
        }
    }

    private void reloadData() {
        try {
            initTable();
            initCmbCategory();
            initCmbVendor();
            fillData(productBUS.getAllProduct());
            initTextField();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void initTextField() {
        txtProductID.setText("");
        txtProductName.setText("");
        txtProductDetail.setText("");
    }
     private void initCmbCategory() {
        try {
            cmbCategory.removeAllItems();
            cmbCategory.addItem(new KeyValue(-1, ""));
            CategoryBUS categoryBUS = new CategoryBUS();
            ArrayList<Category> arrCategory = categoryBUS.getAllCategory();
            for (int i=0;i<arrCategory.size();i++) {
                Category category = arrCategory.get(i);
                cmbCategory.addItem(new KeyValue(i, category.getCategoryName()));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ProductPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initCmbVendor() throws ClassNotFoundException, SQLException {
        cmbVendor.removeAllItems();
        cmbVendor.addItem(new KeyValue(-1, ""));
        VendorBUS vendorBUS = new VendorBUS();
        ArrayList<Vendor> arrVendor = vendorBUS.getAllVendor();
        for (int i =0;i<arrVendor.size();i++) {
            Vendor vendor = arrVendor.get(i);
            cmbVendor.addItem(new KeyValue(i,vendor.getVendorName()));
        }
    }
}
